copyright = "© Coloboradores de Astrofotografía Costa Rica"
defaultContentLanguage = "es"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
languageCode = "es"
timeZone = "America/Costa_Rica"
timeout = "120s"
title = "Astrofotografía Costa Rica"

[params]
  defaultTheme = "dark"
  description = "Galería de aficionados a la Astrofotografía"
  title = "Astrofotografía"
  [params.author]
    email = "ddompe@gmail.com"
    name = "Diego Dompe"
  [params.socialIcons]
    #facebook = "https://www.facebook.com/"
    #instagram = "https://www.instagram.com/"
    #github = "https://github.com/ddompe/astrophotographycr/"
    youtube = "https://www.youtube.com/"
    email = "mailto:ddompe@gmail.com"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/ddompe/astrophographycr"
    weight = 3

[services]
  [services.rss]
    limit = 100
